<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NIS-PC091" name="TestCialfoNew.TestRegister" tests="12" failures="0" timestamp="30 Mar 2017 12:31:55 GMT" time="33.365" errors="2">
  <testcase name="emptyLastNameValidationChecks" time="2.611" classname="TestCialfoNew.TestRegister"/>
  <testcase name="inValidMobileNOvalidationChecks" time="2.787" classname="TestCialfoNew.TestRegister"/>
  <testcase name="validRegistration" time="3.286" classname="TestCialfoNew.TestRegister">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;...login&gt; but was:&lt;...signup&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...login> but was:<...signup>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at TestCialfoNew.TestRegister.validRegistration(TestRegister.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- validRegistration -->
  <testcase name="existingEmailIDValidationChecks" time="2.532" classname="TestCialfoNew.TestRegister"/>
  <testcase name="missMatchPasswordvalidationChecks" time="2.678" classname="TestCialfoNew.TestRegister">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;Password do not match.&gt; but was:&lt;&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<Password do not match.> but was:<>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at TestCialfoNew.TestRegister.missMatchPasswordvalidationChecks(TestRegister.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- missMatchPasswordvalidationChecks -->
  <testcase name="emptyLocationvalidationChecks" time="3.571" classname="TestCialfoNew.TestRegister"/>
  <testcase name="inValidPasswordErrorChecks" time="2.483" classname="TestCialfoNew.TestRegister"/>
  <testcase name="invalidEmailIdvalidationChecks" time="2.654" classname="TestCialfoNew.TestRegister"/>
  <testcase name="emptyPhoneNoValidationChecks" time="2.931" classname="TestCialfoNew.TestRegister"/>
  <testcase name="emptyUserNamevalidationchecks" time="2.583" classname="TestCialfoNew.TestRegister"/>
  <testcase name="emptyEmailIDChecks" time="2.716" classname="TestCialfoNew.TestRegister"/>
  <testcase name="emptyFirstnameValidationChecks" time="2.533" classname="TestCialfoNew.TestRegister"/>
</testsuite> <!-- TestCialfoNew.TestRegister -->
